"""WRA units (branches from the stakeholder model) and the Super User flag on staff accounts (Work Plan A12)."""
# Generated by Django 5.2.17 on 2026-10-05 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=8, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("division", models.CharField(blank=True, max_length=120)),
                (
                    "is_operating",
                    models.BooleanField(
                        default=False,
                        verbose_name="Operating branch (owns data, approves in workflow)",
                    ),
                ),
                (
                    "primary_modules",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='e.g. ["submissions", "licensing", "dashboards", "admin", "exports", "public"]',
                    ),
                ),
                (
                    "has_super_user",
                    models.BooleanField(
                        default=True, verbose_name="Has a Super User (Work Plan A12)"
                    ),
                ),
                ("responsibilities", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "WRA unit",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="is_super_user",
            field=models.BooleanField(
                default=False,
                help_text="One per unit: trained first, co-signs adoption measures at M17, first-line support after handover. Not a permission.",
                verbose_name="Super User (Work Plan A12)",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                help_text="Branch the staff member belongs to (stakeholder model); blank for clients.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="accounts.unit",
                verbose_name="WRA unit",
            ),
        ),
    ]
