# Generated by Django 5.2.17 on 2026-09-21 19:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("lic", "0001_initial"),
        ("ref", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GenericRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approval_state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("under_review", "Under review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        choices=[("staff_only", "Staff only"), ("public", "Public")],
                        db_index=True,
                        default="staff_only",
                        max_length=16,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("migrated", "Migrated from legacy data"),
                            ("aquarius", "Aquarius Time-Series"),
                            ("hga", "Hydro GeoAnalyst"),
                            ("submission", "Data Submission application"),
                            ("api", "API"),
                            ("staff", "Entered by WRA staff"),
                        ],
                        default="staff",
                        max_length=16,
                    ),
                ),
                (
                    "paper_ref",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Location of original paper records",
                    ),
                ),
                (
                    "electronic_ref",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Location of electronic records",
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                (
                    "observed_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "category_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generic_records",
                        to="catalog.categoryversion",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "licence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generic_records",
                        to="lic.licence",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generic_records",
                        to="ref.streamflowstation",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "well",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generic_records",
                        to="ref.well",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("form", "Web form"),
                            ("csv", "CSV upload"),
                            ("api", "API"),
                        ],
                        default="form",
                        max_length=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("validating", "Validating"),
                            ("failed", "Failed validation"),
                            ("under_review", "Under review"),
                            ("info_requested", "Information requested"),
                            ("approved", "Approved and published"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("is_correction", models.BooleanField(default=False)),
                ("correction_reason", models.TextField(blank=True)),
                ("file", models.FileField(blank=True, upload_to="submissions/%Y/%m/")),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("accepted_count", models.PositiveIntegerField(default=0)),
                ("flagged_count", models.PositiveIntegerField(default=0)),
                ("rejected_count", models.PositiveIntegerField(default=0)),
                (
                    "classification",
                    models.CharField(
                        blank=True,
                        choices=[("staff_only", "Staff only"), ("public", "Public")],
                        help_text="Set by the approver at final approval (ToR G.2.vi).",
                        max_length=16,
                        null=True,
                    ),
                ),
                ("submitter_note", models.TextField(blank=True)),
                (
                    "api_idempotency_key",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "category_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submissions",
                        to="catalog.categoryversion",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submissions",
                        to="ref.party",
                    ),
                ),
                (
                    "submitter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="running", max_length=16)),
                ("rows_in", models.PositiveIntegerField(default=0)),
                ("rows_accepted", models.PositiveIntegerField(default=0)),
                ("rows_flagged", models.PositiveIntegerField(default=0)),
                ("rows_rejected", models.PositiveIntegerField(default=0)),
                ("file_sha256", models.CharField(blank=True, max_length=64)),
                ("log", models.TextField(blank=True)),
                (
                    "submission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_runs",
                        to="submissions.submission",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubmissionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_no", models.PositiveIntegerField()),
                ("payload", models.JSONField(default=dict)),
                ("errors", models.JSONField(blank=True, default=dict)),
                ("flags", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("accepted", "Accepted"),
                            ("flagged", "Flagged for review"),
                            ("rejected", "Rejected by validation"),
                            ("promoted", "Promoted to consolidated database"),
                        ],
                        default="accepted",
                        max_length=10,
                    ),
                ),
                ("target_object_id", models.CharField(blank=True, max_length=64)),
                ("promoted_object_id", models.CharField(blank=True, max_length=64)),
                (
                    "promoted_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="submissions.submission",
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["submission", "row_no"],
            },
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["status", "category_version"],
                name="submissions_status_15abc1_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="submissionrecord",
            constraint=models.UniqueConstraint(
                fields=("submission", "row_no"), name="uq_record_row"
            ),
        ),
    ]
