# Generated by Django 5.2.17 on 2026-10-04 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genericrecord",
            name="classification",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("staff_only", "Internal (WRA staff)"),
                    ("restricted", "Restricted"),
                ],
                db_index=True,
                default="staff_only",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="classification",
            field=models.CharField(
                blank=True,
                choices=[
                    ("public", "Public"),
                    ("staff_only", "Internal (WRA staff)"),
                    ("restricted", "Restricted"),
                ],
                help_text="Set by the approver at final approval (ToR G.2.vi).",
                max_length=16,
                null=True,
            ),
        ),
    ]
