# Generated by Django 5.2.17 on 2026-09-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IntegrationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "system",
                    models.CharField(
                        choices=[
                            ("aquarius", "Aquarius Time-Series"),
                            ("hga", "Hydro GeoAnalyst"),
                            ("dspace", "DSpace"),
                            ("arcgis", "ArcGIS Enterprise export"),
                            ("finance", "Finance & Accounts export"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="running", max_length=16)),
                ("records_read", models.PositiveIntegerField(default=0)),
                ("records_written", models.PositiveIntegerField(default=0)),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True)),
                ("output_path", models.CharField(blank=True, max_length=500)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
    ]
