"""Site branding: tile and border colours, copyright line with automatic year."""
# Generated by Django 5.2.17 on 2026-10-05 04:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_sitebranding"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitebranding",
            name="accent_color",
            field=models.CharField(
                default="#b22234",
                help_text="Thin metallic border on tiles and tabs (hex, e.g. #b22234).",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#[0-9a-fA-F]{6}$", "Use a 6-digit hex colour like #1c5ac6."
                    )
                ],
                verbose_name="Border colour",
            ),
        ),
        migrations.AddField(
            model_name="sitebranding",
            name="copyright_text",
            field=models.CharField(
                blank=True,
                default="© {year} {organisation}. All rights reserved.",
                help_text="{year} is replaced with the current year automatically; {organisation} with the organisation name. Leave empty to hide.",
                max_length=200,
                verbose_name="Copyright line",
            ),
        ),
        migrations.AddField(
            model_name="sitebranding",
            name="tile_color",
            field=models.CharField(
                default="#1c5ac6",
                help_text="Background of the home-page tiles and navigation tabs (hex, e.g. #1c5ac6).",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#[0-9a-fA-F]{6}$", "Use a 6-digit hex colour like #1c5ac6."
                    )
                ],
                verbose_name="Tile colour",
            ),
        ),
    ]
