"""Sprint 1: qualifiers, well status events, depth checks, pump-test fields, site master record (instruments, installations, reference points, visits)."""
# Generated by Django 5.2.17 on 2026-09-30 03:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ref", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Instrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            (
                                "level_logger",
                                "Water-level logger / pressure transducer",
                            ),
                            (
                                "stage_recorder",
                                "Stage recorder (float / bubbler / radar)",
                            ),
                            ("rain_gauge", "Rain gauge"),
                            ("flow_meter", "Abstraction flow meter"),
                            ("ec_temp_probe", "Conductivity / temperature probe"),
                            ("current_meter", "Current meter / ADCP (gauging)"),
                            ("telemetry", "Telemetry unit"),
                            ("other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                ("make", models.CharField(blank=True, max_length=100)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("serial_number", models.CharField(max_length=100, unique=True)),
                ("asset_tag", models.CharField(blank=True, max_length=64)),
                ("calibration_due_on", models.DateField(blank=True, null=True)),
                ("is_retired", models.BooleanField(default=False)),
                ("remarks", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["kind", "serial_number"],
            },
        ),
        migrations.CreateModel(
            name="InstrumentInstallation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("installed_on", models.DateField()),
                ("removed_on", models.DateField(blank=True, null=True)),
                (
                    "sensor_offset_m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Sensor position relative to the reference point (m)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("remarks", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["-installed_on"],
            },
        ),
        migrations.CreateModel(
            name="Qualifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=16, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "applies_to",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated series kinds, blank = all",
                        max_length=32,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ReferencePoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "description",
                    models.CharField(
                        help_text="e.g. Top of casing, north side", max_length=150
                    ),
                ),
                (
                    "elevation_m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=8,
                        null=True,
                        verbose_name="Elevation (m above datum)",
                    ),
                ),
                (
                    "height_above_ground_m",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("surveyed_by", models.CharField(blank=True, max_length=150)),
                ("remarks", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["-valid_from"],
            },
        ),
        migrations.CreateModel(
            name="SiteVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("visited_on", models.DateField(db_index=True)),
                (
                    "party_names",
                    models.CharField(
                        blank=True, help_text="Other people present", max_length=200
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("routine", "Routine round"),
                            ("gauging", "Discharge gauging"),
                            ("sampling", "Water-quality sampling"),
                            ("download", "Logger download"),
                            ("maintenance", "Maintenance / repair"),
                            ("calibration", "Calibration"),
                            ("inspection", "Inspection / compliance"),
                            ("installation", "Installation / removal"),
                            ("other", "Other"),
                        ],
                        default="routine",
                        max_length=16,
                    ),
                ),
                ("findings", models.TextField(blank=True)),
                ("actions_taken", models.TextField(blank=True)),
                ("follow_up", models.CharField(blank=True, max_length=255)),
                ("follow_up_due_on", models.DateField(blank=True, null=True)),
                ("photo", models.ImageField(blank=True, upload_to="visits/%Y/%m/")),
            ],
            options={
                "ordering": ["-visited_on"],
            },
        ),
        migrations.CreateModel(
            name="WellStatusEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("drilled", "Drilled"),
                            ("completed", "Completed"),
                            ("pump_installed", "Pump installed"),
                            ("pump_removed", "Pump removed"),
                            ("pumping_started", "Pumping started"),
                            ("pumping_stopped", "Pumping stopped"),
                            ("licensed", "Licence issued"),
                            ("licence_expired", "Licence expired / revoked"),
                            ("rehabilitated", "Rehabilitated"),
                            ("abandoned", "Abandoned"),
                            ("replaced", "Replaced by another well"),
                            ("inspected", "Inspected"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("occurred_on", models.DateField(db_index=True)),
                ("details", models.CharField(blank=True, max_length=255)),
                ("paper_ref", models.CharField(blank=True, max_length=255)),
                ("electronic_ref", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["well", "-occurred_on"],
            },
        ),
        migrations.AlterModelOptions(
            name="wellcasing",
            options={"ordering": ["well", "depth_from_m"]},
        ),
        migrations.AlterModelOptions(
            name="wellownershiphistory",
            options={
                "ordering": ["well", "-from_date"],
                "verbose_name_plural": "well ownership history",
            },
        ),
        migrations.AlterModelOptions(
            name="wellpumptest",
            options={"ordering": ["well", "-tested_on"]},
        ),
        migrations.AddField(
            model_name="wellcasing",
            name="is_screen",
            field=models.BooleanField(
                default=False, help_text="Tick for screened (perforated) intervals"
            ),
        ),
        migrations.AddField(
            model_name="wellpumptest",
            name="duration_hours",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="wellpumptest",
            name="remarks",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="wellpumptest",
            name="specific_capacity_m3_d_m",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=12,
                null=True,
                verbose_name="Specific capacity (m³/d per m drawdown)",
            ),
        ),
        migrations.AddField(
            model_name="wellpumptest",
            name="static_water_level_m",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="wellpumptest",
            name="tested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="ref.party",
            ),
        ),
        migrations.AddField(
            model_name="wellpumptest",
            name="transmissivity_m2_d",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=12,
                null=True,
                verbose_name="Transmissivity (m²/d)",
            ),
        ),
        migrations.AddConstraint(
            model_name="wellcasing",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("depth_to_m__isnull", True),
                    ("depth_from_m__isnull", True),
                    ("depth_to_m__gte", models.F("depth_from_m")),
                    _connector="OR",
                ),
                name="ck_casing_depths",
            ),
        ),
        migrations.AddConstraint(
            model_name="welllithology",
            constraint=models.UniqueConstraint(
                fields=("well", "sequence"), name="uq_lithology_well_sequence"
            ),
        ),
        migrations.AddConstraint(
            model_name="welllithology",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("depth_to_m__isnull", True),
                    ("depth_from_m__isnull", True),
                    ("depth_to_m__gte", models.F("depth_from_m")),
                    _connector="OR",
                ),
                name="ck_lithology_depths",
            ),
        ),
        migrations.AddField(
            model_name="instrument",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="instrument",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="instrumentinstallation",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="instrumentinstallation",
            name="instrument",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="installations",
                to="ref.instrument",
            ),
        ),
        migrations.AddField(
            model_name="instrumentinstallation",
            name="station",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="ref.streamflowstation",
            ),
        ),
        migrations.AddField(
            model_name="instrumentinstallation",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="instrumentinstallation",
            name="well",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="ref.well",
            ),
        ),
        migrations.AddField(
            model_name="referencepoint",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="referencepoint",
            name="station",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="ref.streamflowstation",
            ),
        ),
        migrations.AddField(
            model_name="referencepoint",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="referencepoint",
            name="well",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="ref.well",
            ),
        ),
        migrations.AddField(
            model_name="sitevisit",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sitevisit",
            name="instrument",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="visits",
                to="ref.instrument",
            ),
        ),
        migrations.AddField(
            model_name="sitevisit",
            name="station",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="ref.streamflowstation",
            ),
        ),
        migrations.AddField(
            model_name="sitevisit",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sitevisit",
            name="visited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="site_visits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sitevisit",
            name="well",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="ref.well",
            ),
        ),
        migrations.AddField(
            model_name="wellstatusevent",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="wellstatusevent",
            name="related_well",
            field=models.ForeignKey(
                blank=True,
                help_text="For 'replaced': the replacement well",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="ref.well",
            ),
        ),
        migrations.AddField(
            model_name="wellstatusevent",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="wellstatusevent",
            name="well",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_events",
                to="ref.well",
            ),
        ),
        migrations.AddConstraint(
            model_name="instrumentinstallation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("station__isnull", True), ("well__isnull", False)),
                    models.Q(("station__isnull", False), ("well__isnull", True)),
                    _connector="OR",
                ),
                name="ck_installation_one_site",
            ),
        ),
        migrations.AddConstraint(
            model_name="instrumentinstallation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("removed_on__isnull", True),
                    ("removed_on__gte", models.F("installed_on")),
                    _connector="OR",
                ),
                name="ck_installation_dates",
            ),
        ),
        migrations.AddConstraint(
            model_name="referencepoint",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("station__isnull", True), ("well__isnull", False)),
                    models.Q(("station__isnull", False), ("well__isnull", True)),
                    _connector="OR",
                ),
                name="ck_refpoint_one_site",
            ),
        ),
        migrations.AddConstraint(
            model_name="referencepoint",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_to__isnull", True),
                    ("valid_to__gte", models.F("valid_from")),
                    _connector="OR",
                ),
                name="ck_refpoint_dates",
            ),
        ),
        migrations.AddConstraint(
            model_name="sitevisit",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("station__isnull", True), ("well__isnull", False)),
                    models.Q(("station__isnull", False), ("well__isnull", True)),
                    _connector="OR",
                ),
                name="ck_visit_one_site",
            ),
        ),
    ]
