# Generated by Django 5.2.17 on 2026-10-04 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ref", "0002_sprint1_quality_and_site_master"),
    ]

    operations = [
        migrations.AddField(
            model_name="streamflowstation",
            name="is_public_supply",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Intake for public water supply: exact coordinates and engineering details are restricted outside WRA technical staff.",
                verbose_name="Public-supply source",
            ),
        ),
        migrations.AddField(
            model_name="well",
            name="is_public_supply",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Serves public water supply: exact coordinates and engineering details are restricted outside WRA technical staff.",
                verbose_name="Public-supply source",
            ),
        ),
        migrations.AlterField(
            model_name="spring",
            name="classification",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("staff_only", "Internal (WRA staff)"),
                    ("restricted", "Restricted"),
                ],
                db_index=True,
                default="staff_only",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="streamflowstation",
            name="classification",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("staff_only", "Internal (WRA staff)"),
                    ("restricted", "Restricted"),
                ],
                db_index=True,
                default="staff_only",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="well",
            name="classification",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("staff_only", "Internal (WRA staff)"),
                    ("restricted", "Restricted"),
                ],
                db_index=True,
                default="staff_only",
                max_length=16,
            ),
        ),
    ]
