"""Aquifers, WMU safe yield (design doc 14 §4 — WMU balance sheet)."""
# Generated by Django 5.2.17 on 2026-10-05 16:04

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ref", "0003_restricted_classification"),
    ]

    operations = [
        migrations.AddField(
            model_name="wmu",
            name="safe_yield_m3_d",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Allocation ceiling WRA uses for this unit; from the Water Resources Master Plan.",
                max_digits=14,
                null=True,
                verbose_name="Safe yield (m³/day)",
            ),
        ),
        migrations.AddField(
            model_name="wmu",
            name="safe_yield_source",
            field=models.CharField(
                blank=True,
                help_text="Where the figure comes from and its date, e.g. 'WRMP 2019 table 4.2'.",
                max_length=200,
            ),
        ),
        migrations.CreateModel(
            name="Aquifer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=150)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=3448
                    ),
                ),
                (
                    "aquifer_type",
                    models.CharField(
                        choices=[
                            ("limestone", "Limestone (karst)"),
                            ("alluvial", "Alluvial"),
                            ("volcanic", "Volcanic / igneous"),
                            ("other", "Other"),
                        ],
                        default="limestone",
                        max_length=12,
                    ),
                ),
                (
                    "safe_yield_m3_d",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=14,
                        null=True,
                        verbose_name="Safe yield (m³/day)",
                    ),
                ),
                (
                    "is_saline_risk",
                    models.BooleanField(
                        default=False, verbose_name="Saline intrusion risk"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "basin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aquifers",
                        to="ref.basin",
                    ),
                ),
                (
                    "hydrostrat_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aquifers",
                        to="ref.hydrostratunit",
                    ),
                ),
                (
                    "wmu",
                    models.ForeignKey(
                        blank=True,
                        help_text="Main WMU the aquifer underlies.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aquifers",
                        to="ref.wmu",
                    ),
                ),
            ],
            options={
                "verbose_name": "aquifer",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="well",
            name="aquifer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="wells",
                to="ref.aquifer",
            ),
        ),
    ]
