# Generated by Django 5.2.17 on 2026-10-06 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ref", "0004_technical_assessment"),
    ]

    operations = [
        migrations.AddField(
            model_name="aquifer",
            name="geom_source",
            field=models.CharField(
                blank=True,
                help_text="Where the boundary came from (WRA shapefile, geoBoundaries, demonstration stand-in).",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="basin",
            name="geom_source",
            field=models.CharField(
                blank=True,
                help_text="Where the boundary came from (WRA shapefile, geoBoundaries, demonstration stand-in).",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="hydrostratunit",
            name="geom_source",
            field=models.CharField(
                blank=True,
                help_text="Where the boundary came from (WRA shapefile, geoBoundaries, demonstration stand-in).",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="parish",
            name="geom_source",
            field=models.CharField(
                blank=True,
                help_text="Where the boundary came from (WRA shapefile, geoBoundaries, demonstration stand-in).",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="river",
            name="geom_source",
            field=models.CharField(
                blank=True,
                help_text="Where the boundary came from (WRA shapefile, geoBoundaries, demonstration stand-in).",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="subwmu",
            name="geom_source",
            field=models.CharField(
                blank=True,
                help_text="Where the boundary came from (WRA shapefile, geoBoundaries, demonstration stand-in).",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="wmu",
            name="geom_source",
            field=models.CharField(
                blank=True,
                help_text="Where the boundary came from (WRA shapefile, geoBoundaries, demonstration stand-in).",
                max_length=120,
            ),
        ),
    ]
