# Generated by Django 5.2.17 on 2026-09-21 19:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("allow_submitter_withdraw", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField()),
                ("code", models.SlugField(max_length=64)),
                ("name", models.CharField(max_length=150)),
                (
                    "can_return_to_submitter",
                    models.BooleanField(
                        default=True,
                        help_text="Allow 'request information' back to the submitter.",
                    ),
                ),
                ("can_reject", models.BooleanField(default=True)),
                (
                    "sla_days",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Target turnaround for reporting.",
                        null=True,
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        help_text="Shown to the approver on the review screen.",
                    ),
                ),
                (
                    "approver_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workflow_stages",
                        to="auth.group",
                    ),
                ),
                (
                    "can_return_to",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Earlier stages this stage may return an item to.",
                        related_name="returnable_from",
                        to="workflow.workflowstage",
                    ),
                ),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="workflow.workflowdefinition",
                    ),
                ),
            ],
            options={
                "ordering": ["definition", "order"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("in_progress", "In progress"),
                            ("info_requested", "Information requested from submitter"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        db_index=True,
                        default="in_progress",
                        max_length=16,
                    ),
                ),
                ("object_id", models.CharField(max_length=64)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "stage_entered_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "summary",
                    models.CharField(
                        blank=True,
                        help_text="Shown in queues: e.g. 'WRA-LA-2026-000123 · J. Brown · St. Catherine'",
                        max_length=200,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instances",
                        to="workflow.workflowdefinition",
                    ),
                ),
                (
                    "submitter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_workflows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="workflow.workflowstage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkflowAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("submit", "Submitted"),
                            ("approve", "Approved (advanced to next stage)"),
                            ("final_approve", "Final approval"),
                            ("reject", "Rejected"),
                            ("return", "Returned to earlier stage"),
                            ("request_info", "Information requested from submitter"),
                            ("resubmit", "Resubmitted"),
                            ("withdraw", "Withdrawn"),
                            ("comment", "Comment"),
                            ("classify", "Access classification set"),
                        ],
                        max_length=16,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workflow_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="workflow.workflowinstance",
                    ),
                ),
                (
                    "from_stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="workflow.workflowstage",
                    ),
                ),
                (
                    "to_stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="workflow.workflowstage",
                    ),
                ),
            ],
            options={
                "ordering": ["at", "pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="workflowstage",
            constraint=models.UniqueConstraint(
                fields=("definition", "order"), name="uq_stage_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowstage",
            constraint=models.UniqueConstraint(
                fields=("definition", "code"), name="uq_stage_code"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowinstance",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="workflow_wo_content_5cb705_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowinstance",
            index=models.Index(
                fields=["state", "current_stage"], name="workflow_wo_state_e835a9_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowinstance",
            constraint=models.UniqueConstraint(
                fields=("content_type", "object_id"), name="uq_workflow_subject"
            ),
        ),
    ]
