# Generated by Django 5.2.17 on 2026-10-05 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_wra_units"),
        ("workflow", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowstage",
            name="owning_unit",
            field=models.ForeignKey(
                blank=True,
                help_text="Only members of this WRA unit may act at this stage (stakeholder model). Leave empty to use the item's own owner.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="workflow_stages",
                to="accounts.unit",
            ),
        ),
    ]
