"""Display settings singleton for the dashboards and wall (admin-editable rotation, refresh, order, theme)."""
# Generated by Django 5.2.17 on 2026-10-05 00:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reports", "0003_dashboard_views"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisplaySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rotate_seconds",
                    models.PositiveIntegerField(
                        default=60,
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(3600),
                        ],
                        verbose_name="Seconds per dashboard on the wall",
                    ),
                ),
                (
                    "page_refresh_seconds",
                    models.PositiveIntegerField(
                        default=60,
                        validators=[
                            django.core.validators.MinValueValidator(15),
                            django.core.validators.MaxValueValidator(3600),
                        ],
                        verbose_name="Seconds between the wall re-fetching data",
                    ),
                ),
                (
                    "data_refresh_minutes",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Dashboards show data no older than this. Lower = fresher, more database work.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1440),
                        ],
                        verbose_name="Minutes between recalculations of the bi views",
                    ),
                ),
                (
                    "wall_order",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='e.g. ["licensing", "monitoring", "submissions", "executive"]; empty = all four',
                        verbose_name="Dashboards shown on the wall, in order",
                    ),
                ),
                (
                    "wall_theme",
                    models.CharField(
                        choices=[
                            ("dark", "Dark (recommended for the wall)"),
                            ("light", "Light"),
                        ],
                        default="dark",
                        max_length=5,
                    ),
                ),
                ("show_clock", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "display settings",
                "verbose_name_plural": "display settings",
            },
        ),
    ]
