# Generated by Django 5.2.17 on 2026-09-21 19:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("retired", "Retired"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "json_schema",
                    models.JSONField(blank=True, default=dict, editable=False),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["category", "-version"],
            },
        ),
        migrations.CreateModel(
            name="CategoryRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("date_order", "Date A must not be after date B"),
                            ("range_pair", "Field A must be ≤ field B"),
                            (
                                "sum_of_parts",
                                "Fields must sum to another field (± tolerance)",
                            ),
                            (
                                "licence_limit",
                                "Abstraction volume vs licensed daily volume",
                            ),
                            (
                                "required_if",
                                "Field required when another field has a value",
                            ),
                            ("unique_in_batch", "No two rows may share these fields"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "params",
                    models.JSONField(
                        default=dict,
                        help_text='e.g. {"a": "period_start", "b": "period_end"}',
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("hard", "Hard (blocks acceptance)"),
                            ("soft", "Soft (flag for reviewer)"),
                        ],
                        default="hard",
                        max_length=8,
                    ),
                ),
                ("message", models.CharField(blank=True, max_length=255)),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="catalog.categoryversion",
                    ),
                ),
            ],
            options={
                "ordering": ["version", "pk"],
            },
        ),
        migrations.CreateModel(
            name="CategoryField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "name",
                    models.SlugField(
                        help_text="Column name in CSV/API, e.g. abstraction_volume_m3",
                        max_length=64,
                    ),
                ),
                ("label", models.CharField(max_length=150)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("integer", "Whole number"),
                            ("decimal", "Decimal number"),
                            ("text", "Text"),
                            ("date", "Date"),
                            ("datetime", "Date and time"),
                            ("boolean", "Yes/No"),
                            ("enum", "Choice from a list"),
                            ("well", "Well (reference)"),
                            ("station", "Streamflow station (reference)"),
                            ("licence", "Licence number (reference)"),
                            ("spring", "Spring (reference)"),
                        ],
                        max_length=16,
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=32)),
                ("required", models.BooleanField(default=True)),
                (
                    "min_value",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "max_value",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                ("regex", models.CharField(blank=True, max_length=255)),
                (
                    "choices",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='For enum: ["pumping", "non_pumping"]',
                    ),
                ),
                ("help_text", models.CharField(blank=True, max_length=255)),
                (
                    "target_field",
                    models.CharField(
                        blank=True,
                        help_text="Column on the target model this maps to (blank = keep in payload only).",
                        max_length=64,
                    ),
                ),
                (
                    "soft_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Below this: flag for reviewer, do not block.",
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "soft_max",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="catalog.categoryversion",
                    ),
                ),
            ],
            options={
                "ordering": ["version", "order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="DataCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "target_model",
                    models.CharField(
                        choices=[
                            ("obs.AbstractionRecord", "Water abstraction record"),
                            ("obs.WaterQualitySample", "Water quality sample"),
                            ("obs.WellWaterLevel", "Well water level"),
                            ("obs.StationReading", "Streamflow station reading"),
                            (
                                "submissions.GenericRecord",
                                "Generic (stored as submitted)",
                            ),
                        ],
                        default="submissions.GenericRecord",
                        max_length=64,
                    ),
                ),
                (
                    "link_kind",
                    models.CharField(
                        choices=[
                            ("none", "No site link"),
                            ("well", "Well"),
                            ("station", "Streamflow station"),
                            ("licence", "Licence"),
                            ("spring", "Spring"),
                        ],
                        default="none",
                        max_length=16,
                    ),
                ),
                (
                    "default_classification",
                    models.CharField(
                        choices=[("staff_only", "Staff only"), ("public", "Public")],
                        default="staff_only",
                        max_length=16,
                    ),
                ),
                ("allow_csv", models.BooleanField(default=True)),
                ("allow_api", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "submitter_groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Who may submit (empty = any verified client or staff).",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "data categories",
                "ordering": ["name"],
            },
        ),
    ]
