# Generated by Django 5.2.17 on 2026-09-21 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("workflow", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="datacategory",
            name="workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="categories",
                to="workflow.workflowdefinition",
            ),
        ),
        migrations.AddField(
            model_name="categoryversion",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="catalog.datacategory",
            ),
        ),
        migrations.AddConstraint(
            model_name="categoryfield",
            constraint=models.UniqueConstraint(
                fields=("version", "name"), name="uq_field_name_per_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="categoryversion",
            constraint=models.UniqueConstraint(
                fields=("category", "version"), name="uq_category_version"
            ),
        ),
    ]
