# Generated by Django 5.2.17 on 2026-10-04 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_categoryfield_section"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datacategory",
            name="default_classification",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("staff_only", "Internal (WRA staff)"),
                    ("restricted", "Restricted"),
                ],
                default="staff_only",
                max_length=16,
            ),
        ),
    ]
