"""Model output: ModelRun + ModelOutput tables and the model_run field type (design doc 15 §3.1)."""
# Generated by Django 5.2.17 on 2026-10-05 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_restricted_classification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoryfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("integer", "Whole number"),
                    ("decimal", "Decimal number"),
                    ("text", "Text"),
                    ("date", "Date"),
                    ("datetime", "Date and time"),
                    ("boolean", "Yes/No"),
                    ("enum", "Choice from a list"),
                    ("well", "Well (reference)"),
                    ("station", "Streamflow station (reference)"),
                    ("licence", "Licence number (reference)"),
                    ("spring", "Spring (reference)"),
                    ("model_run", "Model run code (reference)"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="datacategory",
            name="target_model",
            field=models.CharField(
                choices=[
                    ("obs.AbstractionRecord", "Water abstraction record"),
                    ("obs.WaterQualitySample", "Water quality sample"),
                    ("obs.WellWaterLevel", "Well water level"),
                    ("obs.StationReading", "Streamflow station reading"),
                    ("obs.ModelOutput", "Model output (simulated values)"),
                    ("submissions.GenericRecord", "Generic (stored as submitted)"),
                ],
                default="submissions.GenericRecord",
                max_length=64,
            ),
        ),
    ]
