# Generated by Django 5.2.17 on 2026-10-05 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_wra_units"),
        ("catalog", "0005_model_output"),
    ]

    operations = [
        migrations.AddField(
            model_name="datacategory",
            name="owning_unit",
            field=models.ForeignKey(
                blank=True,
                help_text="The WRA unit that owns this data and approves it in the workflow (stakeholder model).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="categories",
                to="accounts.unit",
            ),
        ),
    ]
