# Generated by Django 5.2.17 on 2026-10-08 17:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_wra_units"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdoptionSignoff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("signed_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "measures",
                    models.JSONField(
                        default=dict,
                        help_text="Measure code → true/false as confirmed.",
                    ),
                ),
                ("statement", models.TextField(blank=True)),
                (
                    "signed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adoption_signoffs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adoption_signoffs",
                        to="accounts.unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "adoption sign-off",
                "ordering": ["-signed_at"],
            },
        ),
        migrations.CreateModel(
            name="CleansingIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("duplicate", "Duplicate rows or records"),
                            ("unmatched", "Values that match no reference record"),
                            ("out_of_range", "Values outside the plausible range"),
                            ("mixed_types", "Column mixes numbers, text or dates"),
                            ("date_formats", "Several date formats in one column"),
                            ("placeholder", "Placeholder blanks (N/A, -, 999)"),
                            ("encoding", "Encoding or structure problem"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=16,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        help_text="File, sheet or import run the issue came from.",
                        max_length=200,
                    ),
                ),
                ("column", models.CharField(blank=True, max_length=120)),
                ("summary", models.CharField(max_length=300)),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Examples, unmatched values, candidate matches, counts.",
                    ),
                ),
                ("rows_affected", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("resolved", "Resolved")],
                        db_index=True,
                        default="open",
                        max_length=10,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "keep_existing",
                                "Keep the existing record; discard the incoming value",
                            ),
                            (
                                "use_incoming",
                                "Use the incoming value; replace the existing record",
                            ),
                            ("merge", "Merge: keep both, reconcile the fields"),
                            ("map", "Map the incoming value to an existing record"),
                            ("correct", "Correct at source and re-load"),
                            ("reject", "Reject the rows; do not load"),
                            ("accept", "Accept as is; no action"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "decision_target",
                    models.CharField(
                        blank=True,
                        help_text="For 'map': the reference record the value maps to.",
                        max_length=200,
                    ),
                ),
                ("decision_note", models.TextField(blank=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cleansing_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cleansing_issues",
                        to="accounts.unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "data-cleansing issue",
                "ordering": ["status", "-created_at"],
            },
        ),
    ]
