# Generated by Django 5.2.17 on 2026-09-21 19:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ref", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Licence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "number",
                    models.CharField(editable=False, max_length=32, unique=True),
                ),
                (
                    "water_source",
                    models.CharField(
                        choices=[
                            ("river", "River"),
                            ("spring", "Spring"),
                            ("well", "Well"),
                        ],
                        max_length=8,
                    ),
                ),
                ("source_name", models.CharField(max_length=150)),
                (
                    "daily_volume_granted_m3",
                    models.DecimalField(decimal_places=3, max_digits=14),
                ),
                ("purpose", models.TextField()),
                ("issued_on", models.DateField()),
                ("expires_on", models.DateField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("renewed", "Renewed (superseded)"),
                            ("revoked", "Revoked"),
                            ("suspended", "Suspended"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "expiry_alerts_sent",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Days-before values already alerted, e.g. [90, 30]",
                    ),
                ),
                ("expired_alert_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "classification",
                    models.CharField(
                        choices=[("staff_only", "Staff only"), ("public", "Public")],
                        default="staff_only",
                        max_length=16,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "licensee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="licences",
                        to="ref.party",
                    ),
                ),
                (
                    "parish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="licences",
                        to="ref.parish",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "well",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="licences",
                        to="ref.well",
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_on"],
            },
        ),
        migrations.CreateModel(
            name="LicenceApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reference",
                    models.CharField(editable=False, max_length=32, unique=True),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("new", "New licence"),
                            ("renewal", "Renewal"),
                            ("variation", "Variation of an existing licence"),
                        ],
                        default="new",
                        max_length=12,
                    ),
                ),
                ("applicant_name", models.CharField(max_length=200)),
                ("applicant_address", models.TextField()),
                ("applicant_email", models.EmailField(max_length=254)),
                ("applicant_phone", models.CharField(max_length=32)),
                (
                    "water_source",
                    models.CharField(
                        choices=[
                            ("river", "River"),
                            ("spring", "Spring"),
                            ("well", "Well"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "source_name",
                    models.CharField(max_length=150, verbose_name="Name of source"),
                ),
                (
                    "daily_volume_requested_m3",
                    models.DecimalField(decimal_places=3, max_digits=14),
                ),
                (
                    "daily_volume_granted_m3",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                (
                    "purpose",
                    models.TextField(
                        verbose_name="Purpose for which water will be used"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under review"),
                            ("info_requested", "Information requested"),
                            ("granted", "Granted"),
                            ("refused", "Not granted"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_remarks", models.TextField(blank=True)),
                (
                    "classification",
                    models.CharField(
                        choices=[("staff_only", "Staff only"), ("public", "Public")],
                        default="staff_only",
                        max_length=16,
                    ),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applications",
                        to="ref.party",
                    ),
                ),
                (
                    "applicant_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="licence_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applications",
                        to="ref.parish",
                    ),
                ),
                (
                    "renewal_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="renewal_applications",
                        to="lic.licence",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "well",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applications",
                        to="ref.well",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="licence",
            name="application",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="licence",
                to="lic.licenceapplication",
            ),
        ),
        migrations.CreateModel(
            name="ApplicationDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("id", "Proof of identification"),
                            ("drilling_permit", "Well drilling permit"),
                            ("site_plan", "Site plan"),
                            ("other", "Other supporting document"),
                        ],
                        default="other",
                        max_length=16,
                    ),
                ),
                ("file", models.FileField(upload_to="applications/%Y/%m/")),
                ("original_name", models.CharField(max_length=255)),
                ("content_type", models.CharField(blank=True, max_length=100)),
                ("size", models.PositiveIntegerField(default=0)),
                ("sha256", models.CharField(blank=True, db_index=True, max_length=64)),
                (
                    "scan_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending scan"),
                            ("clean", "Clean"),
                            ("infected", "Infected — quarantined"),
                            ("skipped", "Scanner not configured"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "dspace_handle",
                    models.CharField(
                        blank=True,
                        help_text="Handle of the DSpace item holding this file (ToR G.1.iii)",
                        max_length=100,
                    ),
                ),
                ("dspace_error", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="lic.licenceapplication",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Sequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=32)),
                ("year", models.PositiveIntegerField()),
                ("value", models.PositiveIntegerField(default=0)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("key", "year"), name="uq_sequence_key_year"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TimeStampedNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.TextField()),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="lic.licenceapplication",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="licenceapplication",
            index=models.Index(
                fields=["status", "parish"], name="lic_licence_status_817764_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="licenceapplication",
            index=models.Index(
                fields=["water_source", "status"], name="lic_licence_water_s_3e9f05_idx"
            ),
        ),
    ]
