"""Technical assessment stage: conditions library, assessment record, WMU and conditions on licences (design doc 14 §4)."""
# Generated by Django 5.2.17 on 2026-10-05 16:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lic", "0002_restricted_classification"),
        ("ref", "0004_technical_assessment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LicenceCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=32, unique=True)),
                ("title", models.CharField(max_length=150)),
                (
                    "text",
                    models.TextField(
                        help_text="Wording as it appears on the licence. {volume} is replaced with the granted daily volume, {source} with the source name."
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("metering", "Metering and measurement"),
                            ("reporting", "Reporting of abstraction"),
                            ("monitoring", "Monitoring (levels, quality)"),
                            ("environmental", "Environmental protection"),
                            ("construction", "Well construction and maintenance"),
                        ],
                        default="general",
                        max_length=16,
                    ),
                ),
                (
                    "applies_to",
                    models.CharField(
                        choices=[
                            ("both", "Surface and ground water"),
                            ("river", "River"),
                            ("spring", "Spring"),
                            ("well", "Well"),
                        ],
                        default="both",
                        max_length=8,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Pre-selected on every new assessment."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                "ordering": ["order", "code"],
            },
        ),
        migrations.AddField(
            model_name="licence",
            name="conditions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Licence conditions as issued (text snapshot from the conditions library).",
            ),
        ),
        migrations.AddField(
            model_name="licence",
            name="wmu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="licences",
                to="ref.wmu",
            ),
        ),
        migrations.AddField(
            model_name="licenceapplication",
            name="wmu",
            field=models.ForeignKey(
                blank=True,
                help_text="Set by the technical assessment (defaults to the well's WMU).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applications",
                to="ref.wmu",
                verbose_name="Watershed management unit",
            ),
        ),
        migrations.CreateModel(
            name="TechnicalAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "wmu_safe_yield_m3_d",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Snapshot at assessment time.",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "wmu_allocated_m3_d",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Active licences in the WMU at assessment time (snapshot).",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "wmu_reported_m3_d",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Average reported abstraction, last 12 months (snapshot).",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "impact",
                    models.CharField(
                        choices=[
                            ("none", "None expected"),
                            ("low", "Low"),
                            ("moderate", "Moderate — conditions required"),
                            ("high", "High — refuse or reduce"),
                        ],
                        default="low",
                        max_length=10,
                    ),
                ),
                (
                    "recommendation",
                    models.CharField(
                        choices=[
                            ("grant", "Grant as requested"),
                            ("grant_reduced", "Grant at a reduced volume"),
                            ("more_info", "Request further information / pump test"),
                            ("refuse", "Refuse"),
                        ],
                        default="grant",
                        max_length=14,
                    ),
                ),
                (
                    "recommended_daily_volume_m3",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=14,
                        null=True,
                        verbose_name="Recommended daily volume (m³)",
                    ),
                ),
                (
                    "extra_conditions",
                    models.TextField(
                        blank=True,
                        help_text="Additional conditions specific to this licence, one per line.",
                    ),
                ),
                (
                    "findings",
                    models.TextField(
                        help_text="Source reliability, nearby users, water-quality concerns, pump-test results."
                    ),
                ),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment",
                        to="lic.licenceapplication",
                    ),
                ),
                (
                    "aquifer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessments",
                        to="ref.aquifer",
                    ),
                ),
                (
                    "assessed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assessments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "conditions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assessments",
                        to="lic.licencecondition",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wmu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessments",
                        to="ref.wmu",
                        verbose_name="Watershed management unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "technical assessment",
            },
        ),
    ]
