# Generated by Django 5.2.17 on 2026-09-21 19:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("lic", "0001_initial"),
        ("ref", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StationReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approval_state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("under_review", "Under review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        choices=[("staff_only", "Staff only"), ("public", "Public")],
                        db_index=True,
                        default="staff_only",
                        max_length=16,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("migrated", "Migrated from legacy data"),
                            ("aquarius", "Aquarius Time-Series"),
                            ("hga", "Hydro GeoAnalyst"),
                            ("submission", "Data Submission application"),
                            ("api", "API"),
                            ("staff", "Entered by WRA staff"),
                        ],
                        default="staff",
                        max_length=16,
                    ),
                ),
                (
                    "paper_ref",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Location of original paper records",
                    ),
                ),
                (
                    "electronic_ref",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Location of electronic records",
                    ),
                ),
                ("read_at", models.DateTimeField(db_index=True)),
                (
                    "recorder_reading_m",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True
                    ),
                ),
                (
                    "observer_reading_m",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True
                    ),
                ),
                (
                    "discharge_m3_s",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                ("remarks", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["-read_at"],
            },
        ),
        migrations.CreateModel(
            name="WaterQualitySample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approval_state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("under_review", "Under review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        choices=[("staff_only", "Staff only"), ("public", "Public")],
                        db_index=True,
                        default="staff_only",
                        max_length=16,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("migrated", "Migrated from legacy data"),
                            ("aquarius", "Aquarius Time-Series"),
                            ("hga", "Hydro GeoAnalyst"),
                            ("submission", "Data Submission application"),
                            ("api", "API"),
                            ("staff", "Entered by WRA staff"),
                        ],
                        default="staff",
                        max_length=16,
                    ),
                ),
                (
                    "paper_ref",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Location of original paper records",
                    ),
                ),
                (
                    "electronic_ref",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Location of electronic records",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("well", "Well"),
                            ("spring", "Spring"),
                            ("stream", "Stream"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "sample_ref",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("sampled_at", models.DateTimeField(db_index=True)),
                ("analysed_at", models.DateTimeField(blank=True, null=True)),
                ("sampled_by", models.CharField(blank=True, max_length=150)),
                ("analysed_by", models.CharField(blank=True, max_length=150)),
                (
                    "sample_depth_m",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "specific_conductivity_us_cm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "temperature_c",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "ph",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("colour", models.CharField(blank=True, max_length=50)),
                ("odour", models.CharField(blank=True, max_length=50)),
                (
                    "turbidity_ntu",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "percent_sodium",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "sodium_adsorption_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True
                    ),
                ),
                (
                    "calcium_mg_l",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "magnesium_mg_l",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "potassium_mg_l",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "sodium_mg_l",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "carbonate_mg_l",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "bicarbonate_mg_l",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "sulphate_mg_l",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "chloride_mg_l",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "nitrate_mg_l",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "hardness_mg_l",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "alkalinity_mg_l",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "total_dissolved_solids_mg_l",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                ("extra", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-sampled_at"],
            },
        ),
        migrations.CreateModel(
            name="WellWaterLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approval_state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("under_review", "Under review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        choices=[("staff_only", "Staff only"), ("public", "Public")],
                        db_index=True,
                        default="staff_only",
                        max_length=16,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("migrated", "Migrated from legacy data"),
                            ("aquarius", "Aquarius Time-Series"),
                            ("hga", "Hydro GeoAnalyst"),
                            ("submission", "Data Submission application"),
                            ("api", "API"),
                            ("staff", "Entered by WRA staff"),
                        ],
                        default="staff",
                        max_length=16,
                    ),
                ),
                (
                    "paper_ref",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Location of original paper records",
                    ),
                ),
                (
                    "electronic_ref",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Location of electronic records",
                    ),
                ),
                ("measured_at", models.DateTimeField(db_index=True)),
                ("water_level_m", models.DecimalField(decimal_places=3, max_digits=8)),
                (
                    "well_state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pumping", "Pumping"),
                            ("non_pumping", "Non-pumping"),
                        ],
                        max_length=16,
                    ),
                ),
                ("measured_by", models.CharField(blank=True, max_length=150)),
                ("remarks", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["-measured_at"],
            },
        ),
        migrations.CreateModel(
            name="AbstractionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approval_state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("under_review", "Under review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        choices=[("staff_only", "Staff only"), ("public", "Public")],
                        db_index=True,
                        default="staff_only",
                        max_length=16,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("migrated", "Migrated from legacy data"),
                            ("aquarius", "Aquarius Time-Series"),
                            ("hga", "Hydro GeoAnalyst"),
                            ("submission", "Data Submission application"),
                            ("api", "API"),
                            ("staff", "Entered by WRA staff"),
                        ],
                        default="staff",
                        max_length=16,
                    ),
                ),
                (
                    "paper_ref",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Location of original paper records",
                    ),
                ),
                (
                    "electronic_ref",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Location of electronic records",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("surface", "Surface water"),
                            ("ground", "Underground water"),
                        ],
                        max_length=8,
                    ),
                ),
                ("period_start", models.DateTimeField(db_index=True)),
                ("period_end", models.DateTimeField()),
                (
                    "abstraction_rate_m3_d",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                (
                    "abstraction_volume_m3",
                    models.DecimalField(decimal_places=3, max_digits=16),
                ),
                (
                    "daily_volume_granted_m3",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                ("over_limit", models.BooleanField(db_index=True, default=False)),
                (
                    "over_limit_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "meter_reading",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=16, null=True
                    ),
                ),
                ("remarks", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "licence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="abstractions",
                        to="lic.licence",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="abstractions",
                        to="ref.streamflowstation",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "well",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="abstractions",
                        to="ref.well",
                    ),
                ),
            ],
            options={
                "ordering": ["-period_start"],
            },
        ),
        migrations.CreateModel(
            name="RecordHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.CharField(db_index=True, max_length=64)),
                ("old_values", models.JSONField(default=dict)),
                ("new_values", models.JSONField(default=dict)),
                ("reason", models.TextField()),
                ("corrected_at", models.DateTimeField()),
                ("approved_at", models.DateTimeField(null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="corrections_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "corrected_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="corrections_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "record history",
                "ordering": ["-approved_at"],
            },
        ),
    ]
