# Generated by Django 5.2.17 on 2026-09-21 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("obs", "0001_initial"),
        ("ref", "0001_initial"),
        ("submissions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="recordhistory",
            name="submission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="history_entries",
                to="submissions.submission",
            ),
        ),
        migrations.AddField(
            model_name="stationreading",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stationreading",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="readings",
                to="ref.streamflowstation",
            ),
        ),
        migrations.AddField(
            model_name="stationreading",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="waterqualitysample",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="waterqualitysample",
            name="laboratory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="analysed_samples",
                to="ref.party",
            ),
        ),
        migrations.AddField(
            model_name="waterqualitysample",
            name="spring",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="water_quality",
                to="ref.spring",
            ),
        ),
        migrations.AddField(
            model_name="waterqualitysample",
            name="station",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="water_quality",
                to="ref.streamflowstation",
            ),
        ),
        migrations.AddField(
            model_name="waterqualitysample",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="waterqualitysample",
            name="well",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="water_quality",
                to="ref.well",
            ),
        ),
        migrations.AddField(
            model_name="wellwaterlevel",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="wellwaterlevel",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="wellwaterlevel",
            name="well",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="water_levels",
                to="ref.well",
            ),
        ),
        migrations.AddIndex(
            model_name="abstractionrecord",
            index=models.Index(
                fields=["licence", "period_start"],
                name="obs_abstrac_licence_48e031_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="abstractionrecord",
            index=models.Index(
                fields=["well", "period_start"], name="obs_abstrac_well_id_0717e1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="abstractionrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("period_end__gte", models.F("period_start"))),
                name="ck_abstraction_period",
            ),
        ),
        migrations.AddIndex(
            model_name="stationreading",
            index=models.Index(
                fields=["station", "read_at"], name="obs_station_station_61dc6e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="stationreading",
            constraint=models.UniqueConstraint(
                fields=("station", "read_at"), name="uq_reading_station_time"
            ),
        ),
        migrations.AddIndex(
            model_name="waterqualitysample",
            index=models.Index(
                fields=["well", "sampled_at"], name="obs_waterqu_well_id_2bf366_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="waterqualitysample",
            index=models.Index(
                fields=["station", "sampled_at"], name="obs_waterqu_station_ef16d0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="waterqualitysample",
            index=models.Index(
                fields=["spring", "sampled_at"], name="obs_waterqu_spring__2306b1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="waterqualitysample",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("source_type", "well"), ("well__isnull", False)),
                    models.Q(("source_type", "spring"), ("spring__isnull", False)),
                    models.Q(("source_type", "stream"), ("station__isnull", False)),
                    _connector="OR",
                ),
                name="ck_wq_source_link",
            ),
        ),
        migrations.AddIndex(
            model_name="wellwaterlevel",
            index=models.Index(
                fields=["well", "measured_at"], name="obs_wellwat_well_id_9302de_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="wellwaterlevel",
            constraint=models.UniqueConstraint(
                fields=("well", "measured_at"), name="uq_wwl_well_time"
            ),
        ),
    ]
