"""Sprint 1: grade/qualifier columns on every observation, RecordHistory.method, ApprovalPeriod."""
# Generated by Django 5.2.17 on 2026-09-30 03:19

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obs", "0002_initial"),
        ("ref", "0002_sprint1_quality_and_site_master"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="abstractionrecord",
            name="grade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Ungraded"),
                    ("good", "Good"),
                    ("fair", "Fair"),
                    ("poor", "Poor"),
                    ("estimated", "Estimated"),
                    ("missing", "Missing"),
                ],
                db_index=True,
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="abstractionrecord",
            name="graded_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="abstractionrecord",
            name="graded_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="abstractionrecord",
            name="qualifiers",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=16),
                blank=True,
                default=list,
                help_text="Qualifier codes from ref.Qualifier, e.g. ['PUMPING']",
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="recordhistory",
            name="method",
            field=models.CharField(
                choices=[
                    ("correction", "Correction of an error"),
                    ("gap_fill", "Gap fill (estimated value inserted)"),
                    ("estimate", "Re-estimate of an existing value"),
                    ("shift", "Datum / reference-point shift"),
                    ("regrade", "Grade or qualifier change only"),
                ],
                default="correction",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="stationreading",
            name="grade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Ungraded"),
                    ("good", "Good"),
                    ("fair", "Fair"),
                    ("poor", "Poor"),
                    ("estimated", "Estimated"),
                    ("missing", "Missing"),
                ],
                db_index=True,
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="stationreading",
            name="graded_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="stationreading",
            name="graded_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stationreading",
            name="qualifiers",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=16),
                blank=True,
                default=list,
                help_text="Qualifier codes from ref.Qualifier, e.g. ['PUMPING']",
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="waterqualitysample",
            name="grade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Ungraded"),
                    ("good", "Good"),
                    ("fair", "Fair"),
                    ("poor", "Poor"),
                    ("estimated", "Estimated"),
                    ("missing", "Missing"),
                ],
                db_index=True,
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="waterqualitysample",
            name="graded_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="waterqualitysample",
            name="graded_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="waterqualitysample",
            name="qualifiers",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=16),
                blank=True,
                default=list,
                help_text="Qualifier codes from ref.Qualifier, e.g. ['PUMPING']",
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="wellwaterlevel",
            name="grade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Ungraded"),
                    ("good", "Good"),
                    ("fair", "Fair"),
                    ("poor", "Poor"),
                    ("estimated", "Estimated"),
                    ("missing", "Missing"),
                ],
                db_index=True,
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="wellwaterlevel",
            name="graded_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="wellwaterlevel",
            name="graded_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="wellwaterlevel",
            name="qualifiers",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=16),
                blank=True,
                default=list,
                help_text="Qualifier codes from ref.Qualifier, e.g. ['PUMPING']",
                size=None,
            ),
        ),
        migrations.CreateModel(
            name="ApprovalPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "series",
                    models.CharField(
                        choices=[
                            ("well_level", "Well water level"),
                            ("station_stage", "Station stage / discharge"),
                            ("abstraction", "Abstraction"),
                            ("water_quality", "Water quality"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("approved_at", models.DateTimeField(auto_now_add=True)),
                ("rows_approved", models.PositiveIntegerField(default=0)),
                ("reopened_at", models.DateTimeField(blank=True, null=True)),
                ("remarks", models.CharField(blank=True, max_length=255)),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_periods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reopened_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_periods",
                        to="ref.streamflowstation",
                    ),
                ),
                (
                    "well",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_periods",
                        to="ref.well",
                    ),
                ),
            ],
            options={
                "ordering": ["-starts_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("ends_at__gt", models.F("starts_at"))),
                        name="ck_approval_period_order",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("well__isnull", False),
                            ("station__isnull", False),
                            _connector="OR",
                        ),
                        name="ck_approval_period_site",
                    ),
                ],
            },
        ),
    ]
