# Generated by Django 5.2.17 on 2026-10-04 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obs", "0003_sprint1_quality_and_site_master"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abstractionrecord",
            name="classification",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("staff_only", "Internal (WRA staff)"),
                    ("restricted", "Restricted"),
                ],
                db_index=True,
                default="staff_only",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="stationreading",
            name="classification",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("staff_only", "Internal (WRA staff)"),
                    ("restricted", "Restricted"),
                ],
                db_index=True,
                default="staff_only",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="waterqualitysample",
            name="classification",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("staff_only", "Internal (WRA staff)"),
                    ("restricted", "Restricted"),
                ],
                db_index=True,
                default="staff_only",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="wellwaterlevel",
            name="classification",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("staff_only", "Internal (WRA staff)"),
                    ("restricted", "Restricted"),
                ],
                db_index=True,
                default="staff_only",
                max_length=16,
            ),
        ),
    ]
