"""Model output: ModelRun + ModelOutput tables and the model_run field type (design doc 15 §3.1)."""
# Generated by Django 5.2.17 on 2026-10-05 02:56

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obs", "0004_restricted_classification"),
        ("ref", "0003_restricted_classification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.SlugField(
                        help_text="Short identifier used in CSV uploads, e.g. riocobre-swatplus-2026a.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "model_name",
                    models.CharField(
                        help_text="e.g. SWAT+ rev. 62, Wflow.jl 1.0.4, PRMS 6.0",
                        max_length=80,
                        verbose_name="Model and version",
                    ),
                ),
                (
                    "scenario",
                    models.CharField(
                        blank=True,
                        help_text="Baseline, climate scenario, abstraction scenario…",
                        max_length=120,
                    ),
                ),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                (
                    "time_step",
                    models.CharField(
                        default="daily",
                        help_text="daily, hourly, monthly",
                        max_length=16,
                    ),
                ),
                (
                    "config_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hash of the model configuration (TOML / project folder) for reproducibility.",
                        max_length=64,
                    ),
                ),
                (
                    "calibration_nse",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=6,
                        null=True,
                        verbose_name="Nash–Sutcliffe efficiency",
                    ),
                ),
                (
                    "calibration_kge",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=6,
                        null=True,
                        verbose_name="Kling–Gupta efficiency",
                    ),
                ),
                ("run_by", models.CharField(blank=True, max_length=150)),
                ("run_at", models.DateField(blank=True, null=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Karst treatment, forcing data used, known limitations.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive runs are kept but hidden from dashboards.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "basin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="model_runs",
                        to="ref.basin",
                    ),
                ),
                (
                    "calibration_station",
                    models.ForeignKey(
                        blank=True,
                        help_text="Gauge the metrics were computed against.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calibration_runs",
                        to="ref.streamflowstation",
                    ),
                ),
                (
                    "wmu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="model_runs",
                        to="ref.wmu",
                    ),
                ),
            ],
            options={
                "verbose_name": "model run",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ModelOutput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approval_state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("under_review", "Under review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("staff_only", "Internal (WRA staff)"),
                            ("restricted", "Restricted"),
                        ],
                        db_index=True,
                        default="staff_only",
                        max_length=16,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("migrated", "Migrated from legacy data"),
                            ("aquarius", "Aquarius Time-Series"),
                            ("hga", "Hydro GeoAnalyst"),
                            ("submission", "Data Submission application"),
                            ("api", "API"),
                            ("staff", "Entered by WRA staff"),
                        ],
                        default="staff",
                        max_length=16,
                    ),
                ),
                (
                    "paper_ref",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Location of original paper records",
                    ),
                ),
                (
                    "electronic_ref",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Location of electronic records",
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Ungraded"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                            ("estimated", "Estimated"),
                            ("missing", "Missing"),
                        ],
                        db_index=True,
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "qualifiers",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=16),
                        blank=True,
                        default=list,
                        help_text="Qualifier codes from ref.Qualifier, e.g. ['PUMPING']",
                        size=None,
                    ),
                ),
                (
                    "graded_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "feature_type",
                    models.CharField(
                        choices=[
                            ("station", "Gauged station"),
                            ("well", "Well"),
                            ("reach", "Model reach / channel"),
                            ("subbasin", "Subbasin / HRU"),
                        ],
                        default="station",
                        max_length=10,
                    ),
                ),
                (
                    "feature_ref",
                    models.CharField(
                        blank=True,
                        help_text="Model's own id for the reach, subbasin or HRU (e.g. SWAT+ channel 12).",
                        max_length=64,
                    ),
                ),
                (
                    "variable",
                    models.CharField(
                        choices=[
                            ("discharge_m3_s", "Discharge (m³/s)"),
                            ("water_level_m", "Water level (m)"),
                            ("recharge_mm", "Groundwater recharge (mm)"),
                            ("actual_et_mm", "Actual evapotranspiration (mm)"),
                            ("soil_moisture_mm", "Soil moisture (mm)"),
                            ("precipitation_mm", "Precipitation (mm)"),
                            ("baseflow_m3_s", "Baseflow (m³/s)"),
                            ("other", "Other (see unit)"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                (
                    "observed_at",
                    models.DateTimeField(db_index=True, verbose_name="Simulated for"),
                ),
                ("value", models.DecimalField(decimal_places=4, max_digits=14)),
                ("unit", models.CharField(blank=True, max_length=16)),
                ("remarks", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "graded_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="model_outputs",
                        to="ref.streamflowstation",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "well",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="model_outputs",
                        to="ref.well",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outputs",
                        to="obs.modelrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "model output value",
                "ordering": ["-observed_at"],
                "indexes": [
                    models.Index(
                        fields=["run", "variable", "observed_at"],
                        name="obs_modelou_run_id_ac3815_idx",
                    ),
                    models.Index(
                        fields=["station", "variable", "observed_at"],
                        name="obs_modelou_station_dba0e0_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "run",
                            "feature_type",
                            "station",
                            "well",
                            "feature_ref",
                            "variable",
                            "observed_at",
                        ),
                        name="uq_model_output_point",
                    )
                ],
            },
        ),
    ]
